### ISSUE TITLE
requirements installing problem....

### ISSUE THREAD

**Issue by Raghibshams456** [khanfarhan10/TextSentimentAnalysis#1]
not able to install all requirements can anyone help????
![IMG-20201128-WA0007](https://user-images.githubusercontent.com/48047085/100498549-00e1a300-3189-11eb-8557-a71bb9277174.jpg)

**Comment by khanfarhan10** [comment]
Try using the below dependencies as a replacement for tensorflow and keras :

tensorflow==2.3.0
Keras==2.4.3

**Comment by khanfarhan10** [comment]
Changing the requirements file has fixed this issue. Please try installing with the updated instructions and files. Reopen if issue persists.

**Comment by khanfarhan10** [comment]
Please provide the python version you are using. 
It works fine for Python 3.7.6
Try installing for the same and ask if the problem persists.

Meanwhile I might have to add instructions to use this repo with an older version of python as the current version (3.9.0) has bugs with tensorflow(2.3.0) itself.
