### ISSUE TITLE
Package to PIP

### ISSUE THREAD

**Issue by khanfarhan10** [khanfarhan10/TextSentimentAnalysis#10]
Perhaps use it as a module and host it on Python Packaging Index?

**Comment by khanfarhan10** [comment]
@Vamsi995 @Ankitasareen @Dineshkumar536 anybody willing to perform this task?

**Comment by Vamsi995** [comment]
Im not sure how to do this.

**Comment by khanfarhan10** [comment]
That's okay. Seeing as nobody is interested, I'm closing this issue.
