### ISSUE TITLE
Voice Input

### ISSUE THREAD

**Issue by khanfarhan10** [khanfarhan10/TextSentimentAnalysis#11]
Voice Input of the sentences.
Converting user audio to text and using it as input.

**Comment by Vamsi995** [comment]
Interested

**Comment by Vamsi995** [comment]
This can be done in two ways -> Directly in the front end using the webkitSpeechAPI in javascript (faster)
or it can be done by storing the audio file and passing it to the flask API and then performing the speech recognition here (probably takes more time)
