### ISSUE TITLE
Deploy the Web Application to Heroku

### ISSUE THREAD

**Issue by khanfarhan10** [khanfarhan10/TextSentimentAnalysis#2]
Use [Heroku](https://www.heroku.com/) to deploy the web application (currently : Streamlit & Future Milestone : Flask) to the web.

**Comment by Dineshkumar536** [comment]
pip install gunicorn
At first we need to download gunicorn to our virtual environment venv. We can use pip to download it.

pip freeze > requirements.txt
We need to tell heroku that our project requires all these libraries to successfully run the application. This is done by creating a requirements.txt file.

Procfile is a text file in the root directory of your application, to explicitly declare what command should be executed to start your app. 

heroku login
heroku create
git init
git add .
git commit -m 'initial commit'
git push heroku master
heroku open

**Comment by khanfarhan10** [comment]
Please edit the `requirements.txt` file so that users may not have to manually install each library all the time.

The module should be added as :
`PackageName==VersionName # VerboseComments`

**Comment by khanfarhan10** [comment]
You are assigned the task of deploying the web application. So you might want to change the link in https://github.com/khanfarhan10/TextSentimentAnalysis#web-application-demo

for 

```
Web Application Demo
View the deployed WebApp on Heroku.
```

Also along with that you could add these verbose instructions as a separate section in the README , such as:
`Deploying the WebApp to Heroku`


> pip install gunicorn
> At first we need to download gunicorn to our virtual environment venv. We can use pip to download it.
> 
> pip freeze > requirements.txt
> We need to tell heroku that our project requires all these libraries to successfully run the application. This is done by creating a requirements.txt file.
> 
> Procfile is a text file in the root directory of your application, to explicitly declare what command should be executed to start your app.
> 
> heroku login
> heroku create
> git init
> git add .
> git commit -m 'initial commit'
> git push heroku master
> heroku open

**Comment by khanfarhan10** [comment]
@Dineshkumar536 please rename the name of your PR by describing what bug it solves and what features it adds.

`Final Report` is just a part of the 38 files you've changed so give a valuable Heading to the PR so that people can understand what issues you're trying to solve.

**Comment by Dineshkumar536** [comment]
so i have to change name of my final_report file?

**Comment by khanfarhan10** [comment]
No. You have to change the name of this Pull Request to all the things that you have performed in this Pull Request. Please complete it within today.

**Comment by Dineshkumar536** [comment]
Okay

**Comment by Dineshkumar536** [comment]
Yes now i have changed
