### ISSUE TITLE
Improve Model Analysis - Utility Applications

### ISSUE THREAD

**Issue by khanfarhan10** [khanfarhan10/TextSentimentAnalysis#7]
Provide Utility Tools for the Applications such as Summarization, Paraphrasing etc.

**Comment by Vamsi995** [comment]
For summarization and paraphrasing you need a encoder-decoder (seq2seq) architecture. Using transformers for this will blow up the memory. Only T5, Bart have encoder decoder architecture built in. And their weight files are huge, almost 1GB, so we have to go for a conventional Bi-LSTM or RNN.

**Comment by khanfarhan10** [comment]
Sure, I'm not implying to use any specific technique but try to keep the models as feasible as possible.

**Comment by khanfarhan10** [comment]
@Vamsi995 Are you still willing to work on this as this was a part of your Implementation Ideas in the Project Proposals?

**Comment by Vamsi995** [comment]
The paraphrasing is only that is left. And as I told you, using a transformer model seems heavy as it needs an encoder and a decoder. So a seq2seq model should be made.

**Comment by Vamsi995** [comment]
if space is not an issue, i can use my paraphrasing model, which is stored on cloud, so on inference, it takes some time for the first time, and the other times, it works perfectly fast, because it is stored in cache.

**Comment by khanfarhan10** [comment]
Sure. If you can make all changes today, that'd  be amazing!

**Comment by Vamsi995** [comment]
So I can include my earlier model right?

**Comment by khanfarhan10** [comment]
Sure!
