### ISSUE TITLE
Deploy to an Android App 

### ISSUE THREAD

**Issue by khanfarhan10** [khanfarhan10/TextSentimentAnalysis#9]
Deploy the Generated WebApp to an Android Application (Preferably Flutter).

**Comment by khanfarhan10** [comment]
@Vamsi995 are you still willing to work on this issue as proposed in your report?

**Comment by Vamsi995** [comment]
Preferably be needing another repo to create this flutter application.

**Comment by khanfarhan10** [comment]
Should we go ahead with it or drop it?

Another repo? Why is that??
I think you can create a folder called FlutterApp and get going with adding all the files in there.

**Comment by Vamsi995** [comment]
Because there are a lot of files. Also the interface is going to be pretty intuitive, similar to streamlit.

**Comment by khanfarhan10** [comment]
> Because there are a lot of files. Also the interface is going to be pretty intuitive, similar to streamlit.

Thats all right. You can create a separate folder if required. As of now I don't think a separate repo is required.

**Comment by Vamsi995** [comment]
Cool okay will make it before tonight.

**Comment by khanfarhan10** [comment]
Great. I'm keeping this Issue open and removing the wontfix label then!
